In [5]:
# Solution is available in the other "quiz_solution.py" tab
import tensorflow as tf

def get_weights(n_features, n_labels):
    return tf.Variable(tf.truncated_normal((n_features, n_labels)))
    """
    Return TensorFlow weights
    :param n_features: Number of features
    :param n_labels: Number of labels
    :return: TensorFlow weights
    """
    # TODO: Return weights


def get_biases(n_labels):
    """
    Return TensorFlow bias
    :param n_labels: Number of labels
    :return: TensorFlow bias
    """
    # TODO: Return biases
    return tf.Variable(tf.truncated_normal((1, n_labels)))


def linear(inp, w, b):
    """
    Return linear function in TensorFlow
    :param input: TensorFlow input
    :param w: TensorFlow weights
    :param b: TensorFlow biases
    :return: TensorFlow linear function
    """
    # TODO: Linear Function (xW + b)
    tf.matmul(inp, w) + 

In [3]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from quiz import get_weights, get_biases, linear


def mnist_features_labels(n_labels):
    """
    Gets the first <n> labels from the MNIST dataset
    :param n_labels: Number of labels to use
    :return: Tuple of feature list and label list
    """
    mnist_features = []
    mnist_labels = []

    mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

    # In order to make quizzes run faster, we're only looking at 10000 images
    for mnist_feature, mnist_label in zip(*mnist.train.next_batch(10000)):

        # Add features and labels if it's for the first <n>th labels
        if mnist_label[:n_labels].any():
            mnist_features.append(mnist_feature)
            mnist_labels.append(mnist_label[:n_labels])

    return mnist_features, mnist_labels


# Number of features (28*28 image is 784 features)
n_features = 784
# Number of labels
n_labels = 3

# Features and Labels
features = tf.placeholder(tf.float32)
labels = tf.placeholder(tf.float32)

# Weights and Biases
w = get_weights(n_features, n_labels)
b = get_biases(n_labels)

# Linear Function xW + b
logits = linear(features, w, b)

# Training data
train_features, train_labels = mnist_features_labels(n_labels)

with tf.Session() as session:
    # TODO: Initialize session variables
    
    # Softmax
    prediction = tf.nn.softmax(logits)

    # Cross entropy
    # This quantifies how far off the predictions were.
    # You'll learn more about this in future lessons.
    cross_entropy = -tf.reduce_sum(labels * tf.log(prediction), reduction_indices=1)

    # Training loss
    # You'll learn more about this in future lessons.
    loss = tf.reduce_mean(cross_entropy)

    # Rate at which the weights are changed
    # You'll learn more about this in future lessons.
    learning_rate = 0.08

    # Gradient Descent
    # This is the method used to train the model
    # You'll learn more about this in future lessons.
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

    # Run optimizer and get loss
    _, l = session.run(
        [optimizer, loss],
        feed_dict={features: train_features, labels: train_labels})

# Print loss
print('Loss: {}'.format(l))

[[ 0.5163807   0.4510541   1.1346564   0.4489646   1.3375736 ]
 [ 0.05721911 -1.991419    0.43748114  1.6802514  -0.5634286 ]
 [ 1.771018    0.5016466  -0.3762916   1.0609574  -1.1152768 ]
 [ 1.1660752  -1.5122176   1.1826799   0.92978543 -1.5718247 ]
 [-1.5402457   1.4142694   1.2527646   0.5487784   0.35509375]
 [-0.93930084  1.4226005   0.2838536  -0.165643   -0.04480771]
 [ 0.8290549  -0.44950503  0.14909142  0.61601967 -0.9581105 ]
 [ 0.76694983 -1.3022965  -0.8575185   1.856465   -0.9739994 ]
 [ 0.7307002   0.31903377  1.6695223   1.0460382   0.59988797]
 [ 0.2794839   0.6773302  -1.2584665  -1.0284104   0.7230468 ]
 [ 0.8334647   0.6525321   0.17526813  0.9573377  -0.9439719 ]
 [ 0.3183377   1.619714    0.02756759 -1.5794415  -0.5931467 ]
 [ 0.14822346  1.1591914  -0.3545326   0.9252893   0.96005267]
 [-1.2826897  -0.2369574   0.17072923 -0.4911093  -1.0656211 ]
 [ 1.0796279  -0.6949805  -0.9011509   1.261957    0.32211846]
 [ 0.44941956  0.2651654   0.22392559  0.12572828  1.93

In [4]:
with tf.Session() as sess:
    x = tf.Variable(5)
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(x))

5
